### PR TITLE
Fixes #188: Process with two collapsed Subprocesses creates unexpected test paths

### LINKED ISSUE #188: Process with two collapsed Subprocesses creates unexpected test paths
Hi lovely people,

I really love the idea of the project and wanted to use it in our project, however, right from the get go I have questions regardin the following example process:

grafik

As you can see the path finding of the plugin goes into the collapsed Subprocess A and marks each task/event inside for the test path, as you can see here:

grafik

However, in subprocess B it does not, see here:

grafik

After a little debugging it seems the next outgoing element inside the path finding algorithm returns the Subprocess Activity and not the Start Event inside.

Is this an expected behavior ? Am I missing something?

### PR DESCRIPTION
**Pull request by nyuuyn**
When reaching an EndEvent within a Subprocess and the next element is a subprocess again, it should now properly go through the activities in die next subprocess

### CODE REVIEW

**Comment by gclaussn** [comment]
thx for the PR, I need to check it.

File: camunda-modeler-plugin/main/bpmndt/PathFinder.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ export default class PathFinder {
    * @returns The found elements.
    */
   _findIncoming(subProcessId) {
-    return this.elementRegistry.find(element => {
+    return this.elementRegistry.filter(element => {
```
Comment (gclaussn) [inline camunda-modeler-plugin/main/bpmndt/PathFinder.js:85]: there is mix of `filter` and `find` (line 89) - line 89 should be rewritten to make it more clear

File: camunda-modeler-plugin/main/bpmndt/PathFinder.js [hunk 2]
```diff
@@ -196,8 +196,14 @@ export default class PathFinder {
           return this._getEscalationBoundary($parent.id, eventDefinitions[0].escalationRef?.escalationCode);
         } else {
           // handle end events of embedded sub processes
-          const incoming = this._findIncoming($parent.id);
-          return incoming ? [ incoming.id ] : [];
+          this._findIncoming($parent.id).map(element => {
```
Comment (gclaussn) [inline camunda-modeler-plugin/main/bpmndt/PathFinder.js:199]: do we really expect multiple outgoing sequence flows from a subprocess - normally this is a modeling error

File: camunda-modeler-plugin/main/bpmndt/PathFinder.js [hunk 3]
```diff
@@ -196,8 +196,14 @@ export default class PathFinder {
...
+            if (element.type === BPMN_SUB_PROCESS) {
+              element = this._findStartEvent(element.id);
```
Comment (gclaussn) [inline camunda-modeler-plugin/main/bpmndt/PathFinder.js:201]: we should comment this line, since this is the fix for the actual problem
